title = "Sift"
gitSourceBranch = "main"
changelog = true

classOrder = ["Sift"]

[home]
# enabled = true
includeReadme = true

[[navbar.items]]
label = "Sponsor"
href = "https://github.com/sponsors/cxmeel"
position = "right"

[docusaurus.themeConfig.colorMode]
respectPrefersColorScheme = true
defaultMode = "dark"
