name: ci

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  push:
    branches: [main]

env:
  COMMIT_HASH: ${{github.sha}} # default to the commit hash of the event

jobs:
  format-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
      - uses: ok-nick/setup-aftman@v0.3.0

      - name: Format
        run: stylua --check src/

      - name: Lint
        run: selene src/

  test-docs-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Install Moonwave
        run: npm install -g moonwave

      - name: Build docs
        run: moonwave build

  test-package-build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [format-lint]

    steps:
      - uses: actions/checkout@v2
      - uses: ok-nick/setup-aftman@v0.3.0

      - name: Build
        run: rojo build default.project.json -o build.rbxm

      - name: Set environment variables
        run: echo "COMMIT_HASH=$(git rev-parse --short ${{github.sha}})" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{github.event.repository.name}}-${{env.COMMIT_HASH}}.rbxm
          path: build.rbxm
